name: kook
description: "A cooking companion app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add Flutter localization packages
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  
  # State management
  provider: ^6.1.2
  
  # Storage and preferences
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # HTTP requests
  http: ^1.2.1
  url_launcher: ^6.1.10
  
  # Deep linking - using app_links instead of uni_links
  app_links: ^3.4.5
  
  # UI components
  flutter_spinkit: ^5.2.0
  
  # Encryption packages
  encrypt: ^5.0.3
  crypto: ^3.0.3
  
  # Notification packages
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2
  flutter_phoenix: ^1.1.1
  
  # Added for version checking
  package_info_plus: ^4.2.0  # For getting app version info
  
  # Added for connectivity checking
  connectivity_plus: ^4.0.2  # For internet connectivity check
  # uni_links: ^0.5.1  # Removed and replaced with app_links

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/l10n/en.json
    - assets/l10n/ar.json
    - assets/l10n/fr.json
    - assets/l10n/de.json
    - assets/l10n/fa.json
    - assets/l10n/vi.json


# flutter_launcher_icons configuration for custom app icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

# flutter_native_splash configuration for custom splash screen
flutter_native_splash:
  color: "#ffffff"       # Background color for splash screen
  image: assets/icons/icon.png
  android: true
  ios: true